### ISSUE TITLE
dependency error 

### ISSUE THREAD

**Issue by o0F-0oF** [sinai-dev/BepInExConfigManager#4]
I recently updated to the latest version and got this error on start up 
`[Error  :   BepInEx] Error loading [BepInExConfigManager 1.2.3]: Could not load file or assembly 'Gee.External.Capstone, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

it was working fine before updating.

**Comment by o0F-0oF** [comment]
the same thing happens on unity explorer

**Comment by sinai-dev** [comment]
Thanks, this is actually caused by `Assembly.GetTypes` being called, there is a patch for it in UniverseLib but it broke in the previous version, fixing and releasing an update now.
