### ISSUE TITLE
Use event on ConfigFile rather than per ConfigEntry<T>

### ISSUE THREAD

**Issue by xKiraiChan** [sinai-dev/BepInExConfigManager#5]
`ConfigFile` has an event called `SettingChanged`
The argument for this event is the `ConfigEntryBase` that was changed

Using this event rather than the event on `ConfigEntry<T>` will:
- Allow for other classes deriving from `ConfigEntryBase`
- Remove the reflection that is currently used to subscribe to `ConfigEntry<T>`

The current system causes an exception with non-`ConfigEntry<T>` types and ignores them

**Comment by sinai-dev** [comment]
https://github.com/sinai-dev/BepInExConfigManager/releases/tag/1.2.5
